"use client";

import { useState } from 'react';
import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from '@/components/ui/checkbox';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Wand2, Loader2, UploadCloud, Trash2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { generateBulkItems } from '@/ai/flows/generateBulkItems';
import { useAppContext } from '@/context/AppContext';
import { menuItemSchema } from '@/lib/schemas';
import Image from 'next/image';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { type MenuItem } from '@/lib/types';
import { Progress } from '@/components/ui/progress';

// We define the schema for the items generated by AI for the review table.
// This is now the source of truth for the shape of the data in the form.
export const GeneratedItemSchema = menuItemSchema.extend({
  id: z.string(), // The form array needs an ID
  imageHint: z.string().optional(),
});
export type GeneratedItem = z.infer<typeof GeneratedItemSchema>;


const bulkUploaderSchema = z.object({
  items: z.array(GeneratedItemSchema),
});

type BulkUploaderFormValues = z.infer<typeof bulkUploaderSchema>;

export default function BulkUploader() {
  const { toast } = useToast();
  const { categories, addMenuItem } = useAppContext();
  const [rawInput, setRawInput] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [progress, setProgress] = useState(0);
  const [progressText, setProgressText] = useState('');


  const form = useForm<BulkUploaderFormValues>({
    resolver: zodResolver(bulkUploaderSchema),
    defaultValues: {
      items: [],
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: 'items',
  });

  // Helper function to find or create a category ID
  const getCategoryId = (name: string): string => {
    const existingCategory = categories.find(c => c.name.toLowerCase() === name.toLowerCase());
    if (existingCategory) {
      return existingCategory.id;
    }
    // If we want to auto-create categories, we would do it here.
    // For now, we'll assign to a default if not found.
    const defaultCategory = categories.find(c => c.name.toLowerCase() === 'main-course');
    return defaultCategory ? defaultCategory.id : categories[0]?.id || '';
  };
  
  const handleGenerate = async () => {
    // 1. Pre-processing Input
    const lines = rawInput.split('\n').map(line => line.trim()).filter(line => line.length > 0);
    if (lines.length === 0) {
      toast({ title: 'Input required', description: 'Please enter at least one item name.', variant: 'destructive' });
      return;
    }

    setIsGenerating(true);
    setError(null);
    form.reset({ items: [] });
    setProgress(0);
    setProgressText('');

    let lastSeenCategory = '';
    const generatedItems: GeneratedItem[] = [];
    let failedCount = 0;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        
        const currentProgress = Math.round(((i + 1) / lines.length) * 100);
        setProgress(currentProgress);
        setProgressText(`Processing item ${i + 1} of ${lines.length}...`);

        const isHeading = !/[-–]\s*₹?\s*\d/.test(line);

        if (isHeading) {
            lastSeenCategory = line;
            continue; 
        }

        try {
            const result = await generateBulkItems({ 
                itemInput: line,
                lastSeenCategory: lastSeenCategory 
            });

            if (result && result.name) {
                // The AI returns a category NAME, we need to convert it to a category ID for the form.
                const categoryId = getCategoryId(result.category);
                generatedItems.push({ ...result, category: categoryId });
            } else {
                failedCount++;
            }
        } catch (err: any) {
            console.error(`Failed to process line "${line}":`, err);
            failedCount++;
        }
    }
    
    append(generatedItems);

    if (failedCount > 0) {
        setError(`${failedCount} items could not be processed. Please review them in the raw input and add them manually if needed.`);
    }

    toast({ 
        title: 'Generation Complete!', 
        description: `Successfully processed ${generatedItems.length} items. Please review before uploading.` 
    });

    setIsGenerating(false);
    setProgress(0);
    setProgressText('');
  };

  const onSubmit = async (data: BulkUploaderFormValues) => {
    if(data.items.length === 0) {
        toast({ title: 'No items to upload', description: 'Please generate and review items first.', variant: 'destructive' });
        return;
    }
    setIsSubmitting(true);
    try {
        // We need to omit the temporary 'id' field before sending to Firestore
        const creationPromises = data.items.map(item => {
            const { id, ...itemToCreate } = item;
            return addMenuItem(itemToCreate);
        });

        await Promise.all(creationPromises);

        toast({ title: 'Upload Successful!', description: `${data.items.length} items have been added to the menu.` });
        form.reset({ items: [] });
        setRawInput('');

    } catch (error) {
        console.error('Bulk upload failed:', error);
        toast({ title: 'Upload Failed', description: 'Could not add items to the menu. Please try again.', variant: 'destructive' });
    } finally {
        setIsSubmitting(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-headline">Bulk AI Uploader</CardTitle>
        <CardDescription>
          Paste your full menu below, including category headings. The AI will process each item under its respective category.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid w-full gap-2">
          <Textarea
            placeholder="Soups
Tomato Soup – ₹150
Starters (Veg)
Paneer Tikka – ₹280"
            value={rawInput}
            onChange={(e) => setRawInput(e.target.value)}
            rows={10}
            disabled={isGenerating || isSubmitting}
          />
          <Button onClick={handleGenerate} disabled={isGenerating || isSubmitting || !rawInput.trim()}>
            {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Wand2 className="mr-2 h-4 w-4" />}
            {isGenerating ? 'Generating...' : 'Generate & Review'}
          </Button>
        </div>
        {isGenerating && (
            <div className="space-y-2">
                <Progress value={progress} className="w-full" />
                <p className="text-sm text-muted-foreground text-center">{progressText}</p>
            </div>
        )}
        {error && (
            <Alert variant="destructive">
                <AlertTitle>Generation Issue</AlertTitle>
                <AlertDescription>{error}</AlertDescription>
            </Alert>
        )}
      </CardContent>

      {fields.length > 0 && (
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <CardContent>
                <h3 className="text-lg font-medium mb-4">Review Generated Items</h3>
                <div className="border rounded-lg overflow-x-auto">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead className="w-[200px]">Name</TableHead>
                                <TableHead className="w-[300px]">Description</TableHead>
                                <TableHead className="w-[120px]">Price</TableHead>
                                <TableHead className="w-[180px]">Category</TableHead>
                                <TableHead className="w-[300px]">Image URL</TableHead>
                                <TableHead className="w-[250px]">Flags</TableHead>
                                <TableHead className="w-[50px]">Action</TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {fields.map((field, index) => (
                                <TableRow key={field.id}>
                                    <TableCell><Input {...form.register(`items.${index}.name`)} /></TableCell>
                                    <TableCell><Textarea {...form.register(`items.${index}.description`)} /></TableCell>
                                    <TableCell><Input type="number" {...form.register(`items.${index}.price`, { valueAsNumber: true })} /></TableCell>
                                    <TableCell>
                                        <FormField
                                            control={form.control}
                                            name={`items.${index}.category`}
                                            render={({ field }) => (
                                                <Select onValueChange={field.onChange} value={field.value}>
                                                    <FormControl><SelectTrigger><SelectValue /></SelectTrigger></FormControl>
                                                    <SelectContent>
                                                        {categories.map(cat => <SelectItem key={cat.id} value={cat.id}>{cat.name}</SelectItem>)}
                                                    </SelectContent>
                                                </Select>
                                            )}
                                        />
                                    </TableCell>
                                    <TableCell>
                                        <div className="flex flex-col gap-2">
                                            <Input {...form.register(`items.${index}.imageUrl`)} />
                                            <div className="relative aspect-video w-full rounded-md overflow-hidden border bg-muted">
                                                <Image src={form.watch(`items.${index}.imageUrl`)} alt="Preview" fill className="object-cover" />
                                            </div>
                                        </div>
                                    </TableCell>
                                    <TableCell className="space-y-3">
                                       <FormField control={form.control} name={`items.${index}.isAvailable`} render={({ field }) => (
                                            <FormItem className="flex items-center gap-2 space-y-0"><FormControl><Checkbox checked={field.value} onCheckedChange={field.onChange}/></FormControl><FormLabel className="font-normal">Available</FormLabel></FormItem>
                                        )} />
                                       <FormField control={form.control} name={`items.${index}.isVeg`} render={({ field }) => (
                                            <FormItem className="flex items-center gap-2 space-y-0"><FormControl><Checkbox checked={field.value} onCheckedChange={field.onChange}/></FormControl><FormLabel className="font-normal">Veg</FormLabel></FormItem>
                                        )} />
                                       <FormField control={form.control} name={`items.${index}.isSpicy`} render={({ field }) => (
                                            <FormItem className="flex items-center gap-2 space-y-0"><FormControl><Checkbox checked={field.value} onCheckedChange={field.onChange}/></FormControl><FormLabel className="font-normal">Spicy</FormLabel></FormItem>
                                        )} />
                                       <FormField control={form.control} name={`items.${index}.isChefsSpecial`} render={({ field }) => (
                                            <FormItem className="flex items-center gap-2 space-y-0"><FormControl><Checkbox checked={field.value} onCheckedChange={field.onChange}/></FormControl><FormLabel className="font-normal">Chef's Special</FormLabel></FormItem>
                                        )} />
                                    </TableCell>
                                    <TableCell>
                                        <Button variant="ghost" size="icon" onClick={() => remove(index)}>
                                            <Trash2 className="h-4 w-4 text-destructive" />
                                        </Button>
                                    </TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </div>
            </CardContent>
            <CardFooter>
                <Button type="submit" disabled={isSubmitting || isGenerating}>
                    {isSubmitting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <UploadCloud className="mr-2 h-4 w-4" />}
                    {isSubmitting ? 'Uploading...' : 'Upload All to Menu'}
                </Button>
            </CardFooter>
          </form>
        </Form>
      )}
    </Card>
  );
}
